---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: service-alpine-edge
    image: alpine:edge
    pre_build_image: yes
    command: /sbin/init
    privileged: yes
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: alpine-edge
